SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += ../../src/camera/camera_top.sv
VERILOG_SOURCES += ../../src/camera/camera_if.sv
VERILOG_SOURCES += ../../src/camera/camera_pg.sv

TOPLEVEL = camera_top

MODULE = scenario

include $(shell cocotb-config --makefiles)/Makefile.sim